collect in cluster/array descriptions
rust-embedded/svdtools pull request #178
Opened 2023-10-30 09:07 UTC by burrbull

2023-10-31 08:00 UTC, kossnikita requested changes
Fail with

```yaml
_svd: stm32l4x2.svd
LCD:
  RAM_COM6:
    _array:
      S?? : {}
```

```
RAM_COM6: fields cannot be collected into S?? array. Please, specify description
```

2023-10-31 08:02 UTC, kossnikita commented on src/patch/mod.rs
> +fn replacefirstfrom<'a>(s: &'a str, pat: &str, to: &str, i: usize) -> Cow<'a, str> {
could you also add short descriptions of these functions?

2023-11-05 07:00 UTC, burrbull commented
cc @Emilgardis

2023-11-05 07:04 UTC, kossnikita commented
What about https://github.com/rust-embedded/svdtools/pull/178#pullrequestreview-1705585405?
I don't like that this breaks existing patches that previously worked correctly

2023-11-05 07:43 UTC, burrbull commented
> What about [#178 (review)](https://github.com/rust-embedded/svdtools/pull/178#pullrequestreview-1705585405)? I don't like that this breaks existing patches that previously worked correctly

Sorry missed this comment.
Can't reproduce. Is it `stm32-rs` repo? Could you retry on last `stm32-rs` master and this PR?

2023-11-05 09:21 UTC, burrbull commented
Saying about "RAM_COMx". It looks like there are missed high parts of "64-bit" registers.

2023-11-05 19:43 UTC, kossnikita commented
> Is it `stm32-rs` repo?

This is 
https://github.com/rust-embedded/svdtools/blob/master/example/stm32l4x2.svd

2023-11-08 09:42 UTC, burrbull commented
> > Is it `stm32-rs` repo?
> 
> This is [svdtools/example/stm32l4x2.svd](https://github.com/rust-embedded/svdtools/blob/master/example/stm32l4x2.svd) My example about auto collecting discriptions like `S??`. Before PR this works.

Thanks. I totally forgot about this example.
I think this is one of special cases where we need to specify description manually. (or maybe even `collect` should not work at all).
The issue is names of these fields. They are looks like numerical (and can be parsed as numerical) but instead of `S0, S1, S2, .., S31` they are `S01, S02, S03, .., S31`. So before this patch result looks like (both `description` and `dimIndex` are incorrect):
```xml
        <register>
          <name>RAM_COM6</name>
          <displayName>RAM_COM6</displayName>
          <description>display memory</description>
          <addressOffset>0x44</addressOffset>
          <size>0x20</size>
          <access>read-write</access>
          <resetValue>0x00000000</resetValue>
          <fields>
            <field>
              <dim>32</dim>
              <dimIncrement>0x1</dimIncrement>
              <dimIndex>0-31</dimIndex>
              <name>S%s</name>
              <description>S00</description>
              <bitOffset>0</bitOffset>
              <bitWidth>1</bitWidth>
            </field>
          </fields>
        </register>
```
After patch it fails on descriptions.
But real issue is it should produce ` <dimIndex>00,01,02,..,31</dimIndex>` instead of `<dimIndex>0-31</dimIndex>`.

2023-11-15 08:07 UTC, kossnikita commented
Looks good now

```xml
<field>
  <dim>32</dim>
  <dimIncrement>0x1</dimIncrement>
  <dimIndex>00,01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31</dimIndex>
  <name>S%s</name>
  <description>S%s</description>
  <bitOffset>0</bitOffset>
  <bitWidth>1</bitWidth>
</field>
```

2023-11-15 08:48 UTC, kossnikita commented
I have problem with this but I don't understand the problem

```yaml
  _array:
    DT?,DT[1][0]:
      description: Battery powered domain data register %s
    DT??:
      description: Battery powered domain data register %s
```

```xml
<registers>
    <register>
      <name>DT1</name>
      <displayName>DT1</displayName>
      <description>Battery powered domain data
      register (BPR_DTx)</description>
    </register>
    <register>
      <name>DT2</name>
      <displayName>DT2</displayName>
      <description>Battery powered domain data
      register (BPR_DTx)</description>
    </register>
    <register>
      <name>DT3</name>
      <displayName>DT3</displayName>
      <description>Battery powered domain data
      register (BPR_DTx)</description>
    </register>
    <register>
      <name>DT4</name>
      <displayName>DT4</displayName>
      <description>Battery powered domain data
      register (BPR_DTx)</description>
    </register>
    <register>
      <name>DT5</name>
      <displayName>DT5</displayName>
      <description>Battery powered domain data
      register (BPR_DTx)</description>
    </register>
    <register>
      <name>DT6</name>
      <displayName>DT6</displayName>
      <description>Battery powered domain data
      register (BPR_DTx)</description>
    </register>
    <register>
      <name>DT7</name>
      <displayName>DT7</displayName>
      <description>Battery powered domain data
      register (BPR_DTx)</description>
    </register>
    <register>
      <name>DT8</name>
      <displayName>DT8</displayName>
      <description>Battery powered domain data
      register (BPR_DTx)</description>
    </register>
    <register>
      <name>DT9</name>
      <displayName>DT9</displayName>
      <description>Battery powered domain data
      register (BPR_DTx)</description>
    </register>
    <register>
      <name>DT10</name>
      <displayName>DT10</displayName>
      <description>Battery powered domain data
      register (BPR_DTx)</description>
    </register>
    <register>
      <name>DT11</name>
      <displayName>DT11</displayName>
      <description>Battery powered domain data
      register (BPR_DTx)</description>
    </register>
...
</registers>
```

```
    Caused by:
        0: Processing device `AT32F403`
        1: According to `BPR`
        2: Processing peripheral `BPR`
        3: Collecting registers matched to `DT?,DT[1][0]` in array
        4: BPR: registers cannot be collected into DT?,DT[1][0] array. Please, specify displayName
```

2023-11-15 09:44 UTC, burrbull commented on src/patch/mod.rs
> +    }
This is because of searching first difference.
Alternative is fully delete this part.

2023-11-24 12:05 UTC, burrbull commented
cc @kossnikita , @Emilgardis looks like solution is founded

2023-11-26 05:50 UTC, burrbull commented
let's merge this

2023-11-26 06:25 UTC, kossnikita commented
Wait a little longer please. I haven't finished my tests yet.

2023-11-27 05:02 UTC, kossnikita commented
LGTM. Could you update changelog?

2023-11-27 05:36 UTC, burrbull commented
> LGTM. Could you update changelog?

Sure.

2023-11-27 13:06 UTC, Emilgardis approved these changes

2023-11-27 13:06 UTC, Emilgardis commented on example/common_patches/tsc/tsc.yaml
> +    #  _derivedFrom: "G1_IO1"
is this intentional?

2023-11-27 13:56 UTC, kossnikita commented on example/common_patches/tsc/tsc.yaml
> +    #  _derivedFrom: "G1_IO1"
I'm not sure what it is. This doesn't work right now and results in an error.

2023-11-28 19:12 UTC, merged