show patch on error
rust-embedded/svdtools pull request #183
Opened 2023-11-26 07:07 UTC by burrbull

2023-11-28 19:33 UTC, burrbull commented
cc @rust-embedded/tools

2023-11-29 13:55 UTC, burrbull commented
cc @Emilgardis

2023-11-29 15:48 UTC, Emilgardis requested changes

2023-11-29 15:48 UTC, Emilgardis commented on src/cli.rs
> +        /// When patch error is occured print formatted yaml with all rules included
```suggestion
        /// When a patch error happens print formatted yaml with all rules included
```

2023-11-29 16:32 UTC, Emilgardis approved these changes

2023-11-29 16:37 UTC, merged